- hosts: localhost
  become: true
  gather_facts: false
  vars:
    region: us-east-1
    instance_type: t2.micro
    ami: ami-0b0af3577fe5e3532
    hosts_file: /etc/ansible/hosts
    access_key: AKIA3DOSRQLE4GGQWZML
    secret_key: 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
  tasks:
    - name: Create security group
      ec2_group:
        aws_access_key: '{{ access_key }}'
        aws_secret_key: '{{ secret_key }}'
        name: vniranjan
        description: V Niranjan Security Group
        region: '{{ region }}'
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
    - name: Create an EC2 key
      ec2_key:
        aws_access_key: '{{ access_key }}'
        aws_secret_key: '{{ secret_key }}'
        name: vniranjan
        region: '{{ region }}'
      register: ec2_key
    - name: Save private key (PEM file)
      copy: >-
        content="{{ec2_key.key.private_key}}" dest=/home/ansible/vniranjan.pem
        mode=0600
      when: ec2_key.changed
    - name: Create an ec2 instance
      ec2:
        aws_access_key: '{{ access_key }}'
        aws_secret_key: '{{ secret_key }}'
        key_name: vniranjan
        group: vniranjan
        instance_type: '{{ instance_type}}'
        image: '{{ ami }}'
        wait: true
        region: '{{ region }}'
        count: 1
        count_tag:
          Name: Demo
        instance_tags:
          Name: Demo
      register: ec2
    - name: Save IP to inventory file
      lineinfile:
        dest: '{{hosts_file}}'
        insertafter: '\[webservers\]'
        line: '{{item.private_ip}}'
        line: '{{item.public_ip}}'
      with_items: '{{ec2.instances}}'
    - debug:
         var: '{{ec2}}'
