---
# tasks file for aws
 
 - name: Create security group
   ec2_group:
     aws_access_key: '{{ access_key }}'
     aws_secret_key: '{{ secret_key }}'
     name: casecure
     description: Chandra Security Group
     region: '{{ region }}'
     rules:
       - proto: tcp
         from_port: 22
         to_port: 22
         cidr_ip: 0.0.0.0/0
   register: ec2_info

 - name: Create an EC2 key
   ec2_key:
     aws_access_key: '{{ access_key }}'
     aws_secret_key: '{{ secret_key }}'
     name: casecure
     region: '{{ region }}'
   register: ec2_key 

 - name: Save private key (PEM file)
   copy: >-
     content="{{ec2_key.key.private_key}}" dest={{ lookup('env', 'PWD') }}/casecure.pem
     mode=0600
   when: ec2_key.changed

 - name: Create an ec2 instance
   ec2:
     aws_access_key: '{{ access_key }}'
     aws_secret_key: '{{ secret_key }}'
     key_name: casecure
     group: casecure
     instance_type: '{{ instance_type}}'
     image: '{{ ami }}'
     wait: true
     region: '{{ region }}'
     count: 1
     count_tag:
       Name: Demo
     instance_tags:
       Name: Demo
   register: ec2

 - name: ec2 info using ec2_instance_info module
   ec2_instance_info:
     aws_access_key: '{{ access_key }}'
     aws_secret_key: '{{ secret_key }}'
     filters:
       instance-state-name:
         - running
     region: '{{ region }}'
   register: ec2_infon

 - name: Ip address details
   set_fact:
      vre: '{{count2}}'
   with_items: '{{ec2_infon.instances}}'
   vars:
     count2: "{{index}}"
   loop_control:
     index_var: index
   no_log: true
 - name: Use of variable in IP address
   debug:
     msg: 'S.No {{item|int +1}} IP address is {{(ec2_infon.instances[item|int].public_ip_address)}}'
   with_sequence: start=0 end='{{vre}}'


